modules/models/base.py
class Base:
    def __init__(self, health=None, air_defence=None, air_damage=None, thunder_defence=None, thunder_damage=None,
                 fire_defence=None, fire_damage=None, water_defence=None, water_damage=None, earth_defence=None,
                 earth_damage=None,
                 base_damage=None, average_dps=None):
        self.health = health
        self.fire_damage = fire_damage
        self.fire_defence = fire_defence
        self.water_defence = water_defence
        self.water_damage = water_damage
        self.air_defence = air_defence
        self.air_damage = air_damage
        self.thunder_defence = thunder_defence
        self.thunder_damage = thunder_damage
        self.earth_defence = earth_defence
        self.earth_damage = earth_damage
        self.base_damage = base_damage
        self.average_dps = average_dps

    @staticmethod
    def from_dict(data, average_dps=None):
        return Base(
            health=data.get('baseHealth'),
            air_defence=data.get('baseAirDefence'),
            thunder_defence=data.get('baseThunderDefence'),
            earth_defence=data.get('baseEarthDefence'),
            fire_defence=data.get('baseFireDefence'),
            water_defence=data.get('baseWaterDefence'),
            fire_damage=data.get('baseFireDamage'),
            water_damage=data.get('baseWaterDamage'),
            air_damage=data.get('baseAirDamage'),
            thunder_damage=data.get('baseThunderDamage'),
            earth_damage=data.get('baseEarthDamage'),
            base_damage=data.get('baseDamage'),
            average_dps=average_dps
        )

    def to_dict(self):
        return {
            'health': self.health,
            'air_defence': self.air_defence,
            'thunder_defence': self.thunder_defence,
            'earth_defence': self.earth_defence,
            'fire_defence': self.fire_defence,
            'water_defence': self.water_defence,
            'fire_damage': self.fire_damage,
            'water_damage': self.water_damage,
            'air_damage': self.air_damage,
            'thunder_damage': self.thunder_damage,
            'earth_damage': self.earth_damage,
            'base_damage': self.base_damage,
            'average_dps': self.average_dps  # Include averageDps in the output
        }

modules/routes/web.py
from flask import Blueprint, render_template, abort
from datetime import datetime, timezone

from modules import wynn_api
from modules.routes import api

web_bp = Blueprint('web', __name__)


@web_bp.route("/")
@web_bp.route("/index")
def index():
    return lootrun_lootpool()

@web_bp.route("/items")
def items():
    return render_template("items.html")

@web_bp.route("/item")  # TODO: TEST ONLY
def item():
    items = wynn_api.search_item(query="Collapse")
    return render_template("single_item.html", items=items)

@web_bp.route("/lootrun")
def lootrun_lootpool():
    loot_data = api.get_lootpool_items("lootpool")[0].get_json()
    loot_data = loot_data if isinstance(loot_data, list) else []

    now = datetime.now(timezone.utc)

    for item in loot_data:
        timestamp = datetime.strptime(item["timestamp"], '%a, %d %b %Y %H:%M:%S %Z').replace(tzinfo=timezone.utc)
        time_diff = now - timestamp
        minutes = time_diff.total_seconds() // 60
        if minutes < 60:
            item["last_updated"] = f"Last updated {int(minutes)} minutes ago"
        else:
            hours = minutes // 60
            item["last_updated"] = f"Last updated {int(hours)} hour{'s' if hours > 1 else ''} ago"

    return render_template("lootrun_lootpool.html", loot_data=loot_data)

@web_bp.route("/raid")
def raid_lootpool():
    loot_data = api.get_lootpool_items("raidpool")[0].get_json()
    loot_data = loot_data if isinstance(loot_data, list) else []

    now = datetime.now(timezone.utc)

    for item in loot_data:
        timestamp = datetime.strptime(item["timestamp"], '%a, %d %b %Y %H:%M:%S %Z').replace(tzinfo=timezone.utc)
        time_diff = now - timestamp
        minutes = time_diff.total_seconds() // 60
        if minutes < 60:
            item["last_updated"] = f"Last updated {int(minutes)} minutes ago"
        else:
            hours = minutes // 60
            item["last_updated"] = f"Last updated {int(hours)} hour{'s' if hours > 1 else ''} ago"

    return render_template("raid_lootpool.html", loot_data=loot_data)

@web_bp.route("/players")
def players():
    return lootrun_lootpool()

@web_bp.route("/history/", defaults={'item_name': None})
@web_bp.route("/history/<item_name>")
@web_bp.route("/history/<item_name>/")
def history(item_name):
    return render_template("price_history.html", item_name=item_name)

@web_bp.route("/ranking")
def ranking():
    return render_template("price_ranking.html")

templates/components/_base.html
<!doctype html>
<html lang="en" data-bs-theme="dark">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>WynnVentory - {% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='mc_icons.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='minecraft_font.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
</head>

<body>
    <div class="container-fluid overflow-hidden">
        <div class="row main overflow-hidden">
            <!-- NAVBAR -->
            <div class="navbar col-12 col-sm-3 col-xl-2 px-sm-2 px-0 sidebar sticky-top mb-3 mb-sm-0">
                <div
                    class="d-flex flex-row flex-sm-column justify-content-between h-100 w-100 align-items-center align-items-sm-start px-3 pt-2 pt-sm-4">
                    <a href="{{ url_for('web.items') }}"
                        class="d-flex align-items-center pb-sm-3 mb-md-0 me-md-auto text-decoration-none logo-div d-none d-md-block">
                        <span class="fs-logo"><span class="d-none d-sm-inline">Wynnventory</span></span>
                    </a>
                    <ul class="nav nav-pills flex-sm-column flex-row flex-nowrap flex-shrink-1 flex-sm-grow-0 flex-grow-1 mb-sm-auto mb-0 justify-content-center align-items-center align-items-sm-start nav-div"
                        id="menu">
                        <li class="nav-item">
                            <a href="{{ url_for('web.items') }}" class="nav-link px-sm-0 px-2">
                                <i class="icon-minecraft icon-minecraft-iron-sword"></i><span
                                    class="ms-1 d-none d-sm-inline">Items</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{ url_for('web.lootrun_lootpool') }}" class="nav-link px-sm-0 px-2">
                                <i class="icon-minecraft icon-minecraft-chest"></i><span
                                    class="ms-1 d-none d-sm-inline">Lootpool</span> </a>
                        </li>
                        <li>
                            <a href="{{ url_for('web.raid_lootpool') }}" class="nav-link px-sm-0 px-2">
                                <span class="sprite bg-mageaspect" style="vertical-align: middle;"></span>
                                <span class="ms-1 d-none d-sm-inline">Raidpool</span> </a>
                        </li>
                        <li class="w-100 border-top my-2 d-none d-md-block"></li>
                        <li>
                            <a href="{{ url_for('web.history') }}" class="nav-link px-sm-0 px-2">
                                <i class="icon-minecraft icon-minecraft-spyglass"></i><span
                                    class="ms-1 d-none d-sm-inline">Price Insights</span>
                            </a>
                        </li>
                        {# <li>
                            <a href="{{ url_for('web.players') }}" class="nav-link px-sm-0 px-2">
                                <i class="icon-minecraft icon-minecraft-player-head"></i></i><span
                                    class="ms-1 d-none d-sm-inline">Players</span></a>
                        </li> #}
                        <li class="d-none d-md-block">
                            <a href="{{ url_for('web.ranking') }}" class="nav-link px-sm-0 px-2">
                                <i class="icon-minecraft icon-minecraft-totem-of-undying"></i><span
                                    class="ms-1 d-none d-sm-inline">Price Ranking</span>
                            </a>
                        </li>
                    </ul>
                    <div class="py-sm-4 mt-sm-auto ms-auto ms-sm-0 flex-shrink-1 btn-div d-flex flex-column align-items-center align-items-sm-start gap-2">
                        <div class="d-flex align-items-center">
                            <input class="form-check-input" type="checkbox" id="darkModeSwitch" checked>
                            <label class="form-check-label ps-2 fs-mobile fs-desktop" for="darkModeSwitch">Dark Mode</label>
                        </div>
                    
                        <div class="d-none d-md-flex flex-column align-items-center align-items-sm-start w-100 pt-3 border-top discord-cta">
                            <a href="https://discord.gg/b6ATfrePuR" target="_blank"
                                class="d-flex align-items-center gap-2 w-100 text-decoration-none py-2 px-2 rounded discord-link">
                                <i class="bi bi-discord" style="color: #5865F2; font-size: 1.3rem;"></i>
                                <span class="small fw-medium d-none d-xl-inline">Join our Discord</span>
                            </a>
                        </div>                        
                    </div>                    
                </div>
            </div>

            <!-- CONTENT -->
            <div class="col d-flex flex-column h-sm-100 p-4">
                <main class="row overflow-auto content px-4">
                    {% block content %}{% endblock %}
                </main>
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='app.js') }}"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.js"
        integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
</body>

</html>